// import NavBar from "./components/NavBar";
// import "./globals.css";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
// 	return (
// 		<html lang="en">
// 			<body
// 				className={`${inter.className} flex min-h-screen flex-col bg-gray-900 text-gray-200`}
// 			>
// 				<NavBar />
// 				<main className="flex flex-1 flex-col">{children}</main>
// 			</body>
// 		</html>
// 	);
// }
import NavBar from "./components/NavBar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout(props) {
	return (
		<html lang="en">
			<body
				className={`${inter.className} flex min-h-screen flex-col bg-gray-900 text-gray-200`}
			>
				<NavBar />
				<main className="flex flex-1 gap-2">
					{props.children}
					{props.analytics}
					{props.team}
				</main>
			</body>
		</html>
	);
}
